### PR TITLE
Allow build with qt6

### PR DESCRIPTION
**Pull request by neochapay**

### CODE REVIEW

**Review by Thaodan — CHANGES_REQUESTED** [review]
Please read:
Similar to https://github.com/sailfishos/qt-mobility-haptics-ffmemless/pull/1#pullrequestreview-1598788046

**Review by Thaodan — CHANGES_REQUESTED** [review]
Please don't add "Fixes" to the bug as it will close the bug but it depends on multiple PR's.
Either add "Contributes to JB#XZY" or "JB#XZY" if there's not enough space left in the first line of the commit message.

**Comment by neochapay** [comment]
@Thaodan fixed

**Review by Thaodan — APPROVED** [review]
LGTM

**Pull request merged**
